name: fkill
version: latest
version-script: git -C parts/fkill/build describe --tags | sed 's/v//'
summary: Fabulously kill processes. Cross-platform.
description: |
  A command-line tool for easily and quickly killing processes.

grade: stable
confinement: strict

apps:
  fkill:
    command: fkill
    plugs:
      - network
      - process-control
      - system-observe

parts:
  fkill:
    plugin: nodejs
    node-engine: 8.11.1
    source: https://github.com/sindresorhus/fkill-cli.git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info fkill | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl build
    stage-packages:
      - iproute2
      - libatm1
      - psmisc
