name: fkill
version: '5.2.0'
summary: Fabulously kill processes. Cross-platform.
description: |
  A command-line tool for easily and quickly killing processes.

grade: stable
confinement: strict

apps:
  fkill:
    command: fkill
    plugs:
      - network
      - process-control
      - system-observe

parts:
  fkill:
    plugin: nodejs

    source: https://github.com/sindresorhus/fkill-cli.git
    source-tag: 'v5.2.0'

  mypackages:
    plugin: nil
    stage-packages:
      - psmisc

