name: fkill
adopt-info: fkill
summary: Fabulously kill processes. Cross-platform.
description: |
  A command-line tool for easily and quickly killing processes.
base: core20

grade: stable
confinement: strict

apps:
  fkill:
    command: bin/fkill
    plugs:
      - network
      - process-control
      - system-observe

parts:
  fkill:
    plugin: npm
    npm-node-version: 16.15.1
    source: https://github.com/sindresorhus/fkill-cli.git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info fkill | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl build
      snapcraftctl set-version $last_committed_tag
    stage-packages:
      - iproute2
      - libatm1
      - psmisc
